language: python
python: '3.7'
install:
- pip install pipenv
- pipenv sync
script:
- pipenv run autopep8 -r . --diff --exit-code
- pipenv run flake8 .
- cd server && pipenv run python -m unittest discover
